public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    public UserProfile(String [] userInfo) {
       
        username = userInfo[0];
        age = Integer.parseInt(userInfo[1]);
        if (userInfo[4].equals("pounds"))
            weight = (Integer.parseInt(userInfo[3]))/KILOGRAM;
        else 
            weight = Integer.parseInt(userInfo[3]);
        if (userInfo[5].contains(","))
        	height = Integer.parseInt(userInfo[5].substring(0, 1)) * 30.48 + Integer.parseInt(userInfo[5].substring(2, userInfo[5].length())) * 2.54;
        CalorieCalculator(userInfo[2], userInfo[6]);
        initComponents();
    }
    
    private void CalorieCalculator(String gender, String exerciseLevel){  
   
         if (gender.equals("male")){
            BMR = (int) ( (10 * weight) + (6.25 * height) - (5 * age) + 5);
            if (Integer.parseInt(exerciseLevel) == 1)
                calorieLevel = BMR + 361;
            else
                calorieLevel = BMR + 361 + (82 * Integer.parseInt(exerciseLevel));
            System.out.println(calorieLevel);
         }
        else {
            BMR = (int) ( (10 * weight) + (6.25 * height) - (5 * age) - 161);
            calorieLevel = BMR + (361 * Integer.parseInt(exerciseLevel));
         }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        greetingTitle = new javax.swing.JLabel();
        calorieTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        calorieList = new javax.swing.JList<>();
        BMRTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        greetingTitle.setFont(new java.awt.Font("L M Roman10", 0, 24)); // NOI18N
        greetingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetingTitle.setText("Welcome");
        greetingTitle.setText("Welcome " + username );

        calorieTitle.setFont(new java.awt.Font("L M Roman10", 0, 24)); // NOI18N
        calorieTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calorieTitle.setText("Daily Calories");

        calorieList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        calorieList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {"You need " + String.valueOf(calorieLevel) + " Calories/day to maintain your weight",
                "You need " + String.valueOf(calorieLevel - 500) + " Calories/day to lose 1 lb per week",
                "You need " + String.valueOf(calorieLevel - 1000) + " Calories/day to lose 2 lb per week",
                "You need " + String.valueOf(calorieLevel + 500) + " Calories/day to gain 1 lb per week",
                "You need " + String.valueOf(calorieLevel + 1000) + " Calories/day to lose 1 lb per week",
            };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(calorieList);

        BMRTitle.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        BMRTitle.setText("Basal Metabolic Rate");
        BMRTitle.setText("Basal Metabolic Rate: " + BMR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(calorieTitle)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BMRTitle)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(greetingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greetingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addComponent(calorieTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BMRTitle)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }
    
    private static int age;
    private static int exerciseLevel;
    private static double weight;
    private static double height;
    private static String username;
    private static final double KILOGRAM = 2.2046226218;
    private static int BMR;
    private static int calorieLevel;
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel BMRTitle;
    private javax.swing.JList<String> calorieList;
    private javax.swing.JLabel calorieTitle;
    private javax.swing.JLabel greetingTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
